-- Sql Analysis of our 3 coffee shops

SELECT TOP (1000) [PURCHASE_DATE]
      ,[DAY_OF_MONTH]
      ,[NAME_OF_MONTH]
      ,[MONTH_ID]
      ,[DAY_NAME]
      ,[DAY_CLASSIFICATION]
      ,[HOUR_OF_DAY]
      ,[TIME_BUCKETS]
      ,[TOTAL_REVENUE]
      ,[NUMBER_OF_SALES]
      ,[STORES]
      ,[NUMBER_OF_DIFFERENT_PRODUCTS]
      ,[PRODUCT_CATEGORY]
      ,[PRODUCT_DETAIL]
      ,[PRODUCT_TYPE]
      ,[STORE_LOCATION]
  FROM [coffeeShop_db].[dbo].[coffeeShop_sales]
